apiVersion: v1
kind: Secret
metadata:
  name: iam-secret
  namespace: securebankito
type: Opaque
stringData:
  POSTGRES_PASSWORD: "iam_pass"
  JWT_SECRET: "securebankito-jwt-secret-2024"
  DATABASE_URL: "postgresql://iam_user:iam_pass@iam-postgres:5432/iam_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-config
  namespace: securebankito
data:
  PORT: "3001"
  POSTGRES_DB: "iam_db"
  POSTGRES_USER: "iam_user"
  POSTGRES_HOST: "iam-postgres"
  POSTGRES_PORT: "5432"
