apiVersion: v1
kind: Secret
metadata:
  name: corebancario-secret
  namespace: securebankito
type: Opaque
stringData:
  POSTGRES_PASSWORD: "core_pass"
  JWT_SECRET: "securebankito-jwt-secret-2024"
  DATABASE_URL: "postgresql://core_user:core_pass@core-postgres:5432/corebancario_db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: corebancario-config
  namespace: securebankito
data:
  PORT: "3002"
  POSTGRES_DB: "corebancario_db"
  POSTGRES_USER: "core_user"
  POSTGRES_HOST: "core-postgres"
  POSTGRES_PORT: "5432"
